---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgresdb
    service: postgresdb
  name: postgresdb
  namespace: githubissuemanager
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
  selector:
    app: postgresdb
    service: postgresdb
