---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: githubissuemanager-pv
  labels:
    app: githubissuemanager
spec:
  storageClassName: local-storage
  claimRef:
    namespace: githubissuemanager
    name: githubissuemanager-claim
  capacity:
    storage: 256Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/pv0001/
    type: DirectoryOrCreate
