---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: website
    service: website
  name: website
  namespace: githubissuemanager
spec:
  type: ClusterIP
  ports:
    - name: "3000"
      port: 3000
  selector:
    app: website
    service: website
